server:
  port: 8020
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    JDBC : SGDB :// HOST : PORT / DB
    url: jdbc:postgresql://localhost:5432/nutricare
    username: postgres
    password: 12345
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect